# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e6578c86e006a08f2456af1ba52fe4f528b9e39bdc318cfc5edd2853ff4aa4f476913729f7fbc45726f65495c997035cea58080e925ed9caa87ef66e9615aaf

test:
  secret_key_base: 1e5a07c20589044bb248045bc7a0f621ab4132e013db82c88622de0aa53b8968e3c293ccfc2a4abb7b65180f1a9ccfa66cd4ac26f609a266113b879056f4ef94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
